name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  version:
    name: Version
    uses: cupel-co/workflows/.github/workflows/version.generate.yml@3f6e3882754ef9f709b10936e6792212b92ccce2
    permissions:
      contents: read
