name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  version:
    name: Version
    uses: cupel-co/workflows/.github/workflows/version.generate.yml@e126a14c220d8daa8d84e59431446dbb18a24e7d
