name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  version:
    name: Version
    uses: cupel-co/workflows/.github/workflows/version.generate.yml@3b973fd38ee46e7b2c4f9918d75406dc52e615b1
    permissions:
      contents: read
