name: Notify PR opened

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  pull-request:
    name: Pull Request
    uses: cupel-co/workflows/.github/workflows/pull-request.notify.yml@3b973fd38ee46e7b2c4f9918d75406dc52e615b1
    permissions:
      issues: read
      pull-requests: read
      repository-projects: read
    secrets:
      google-chat-webhook-url: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
