name: Update PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  pull-request:
    name: Pull Request
    uses: cupel-co/workflows/.github/workflows/pull-request.update.yml@3f6e3882754ef9f709b10936e6792212b92ccce2
    permissions:
      issues: read
      pull-requests: write
      repository-projects: read
    with:
      environment: Production
