name: Update PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  pull-request:
    name: Pull Request
    uses: cupel-co/workflows/.github/workflows/pull-request.update.yml@3b973fd38ee46e7b2c4f9918d75406dc52e615b1
    permissions:
      issues: read
      pull-requests: write
      repository-projects: read
    with:
      environment: Production
